# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Deploy app to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: create environment file
        run: |
          touch .env
          echo BOT_TOKEN =${{ secrets.BOT_TOKEN }} >> .env
          echo BOT_APP_ID =${{ secrets.BOT_APP_ID }} >> .env
          echo BOT_PUBLIC_KEY =${{ secrets.BOT_PUBLIC_KEY }} >> .env
          echo BOT_CLIENT_SECRET =${{ secrets.BOT_CLIENT_SECRET }} >> .env
          echo DM_ID =${{ secrets.DM_ID }} >> .env
          echo DM_TOKEN =${{ secrets.DM_TOKEN }} >> .env
          echo CHANGELOG_ID =${{ secrets.CHANGELOG_ID }} >> .env
          echo CHANGELOG_TOKEN =${{ secrets.CHANGELOG_TOKEN }} >> .env
          echo STATUS_ID =${{ secrets.STATUS_ID }} >> .env
          echo STATUS_TOKEN =${{ secrets.STATUS_TOKEN }} >> .env
          echo ADVISOR_ID =${{ secrets.ADVISOR_ID }} >> .env
          echo ADVISOR_TOKEN =${{ secrets.ADVISOR_TOKEN }} >> .env
          echo SERVER_ID =${{ secrets.SERVER_ID }} >> .env
          echo DB_USERNAME =${{ secrets.DB_USERNAME }} >> .env
          echo DB_PASSWORD =${{ secrets.DB_PASSWORD }} >> .env
          echo DB_SERVER =${{ secrets.DB_SERVER }} >> .env
          echo DB_PORT =${{ secrets.DB_PORT }} >> .env
          echo DB_NAME =${{ secrets.DB_NAME }} >> .env

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'project-bot'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_F483E71EBAAB43DFBEB8F4F3D7FFFA95 }}
          package: .
